// Copyright (c) 2026 The Hemis Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

// W3.1-Test1 — Known-polynomial subset exhaustion (direct-call).
// Gate: W1.2 (ceremony code) blocked until this passes in full.
//
// Validates PartialSign -> Recover -> Verify produces internally consistent
// output across all C(n,t) subsets, three polynomial configurations. No
// external oracle (IMP-D5: chiabls rejected — RELIC unreviewed, DST mismatch).
// PTX_BLS_Verify called with explicit group_pk (KDD-049).
//
// KDD-069 (dealer retirement): the polynomial is generated by the TEST-LOCAL
// gen_known_polynomial() below — pure blst arithmetic, NO node_index, NO
// alphabetical sort, NO production dealer symbol (PTX_BLS_Init /
// g_ptx_bls_state are gone). The property under test is the protocol-independent
// t-of-n BLS threshold guarantee, not any dealer mechanism; the generator is a
// synthetic known polynomial standing in for a completed DKG's shares + group_pk.
//
// Direct-call test: synthetic polynomial, no daemon, no accessor.
//
// Limitation: group_pk correctness (does the generator produce the correct
// group key for the polynomial?) is not independently verified — in scope
// for W3.2 external audit.
//
// Harness integrity: harness_rejects_corruption() is called as the first
// statement of run_subset_exhaustion(), before any subset is processed. It
// is also exposed as BLSSubset_FalsificationCheck for named CI output. Both
// paths use BOOST_REQUIRE, so a broken harness produces explicit failures in
// every TV case — no TV can silently pass with a broken verify gate.
// Boost.Test execution order is not relied upon.

#include "test/test_Hemis.h"
#include "ptx/ptx_bls.h"
#include "random.h"

#include <boost/test/unit_test.hpp>

#include <array>
#include <cstring>
#include <numeric>
#include <string>
#include <vector>

BOOST_FIXTURE_TEST_SUITE(ptx_bls_subset_tests, BasicTestingSetup)

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// Advances combo (0-indexed, size k, drawn from {0,...,n-1}) to next
// lexicographic combination. Returns false when all C(n,k) are exhausted.
static bool next_combination(std::vector<int>& c, int n)
{
    int k = (int)c.size();
    for (int i = k - 1; i >= 0; --i) {
        if (c[i] < n - k + i) {
            ++c[i];
            for (int j = i + 1; j < k; ++j)
                c[j] = c[j - 1] + 1;
            return true;
        }
    }
    return false;
}

// Build a uint256 whose 32 bytes are all `fill`.
static uint256 make_msg(uint8_t fill)
{
    uint256 m;
    memset(m.begin(), fill, 32);
    return m;
}

// ---------------------------------------------------------------------------
// Test-local known-polynomial generator (KDD-069).
//
// Replaces the retired trusted-dealer PTX_BLS_Init. Produces exactly what the
// subset property needs, with no dealer state and no index basis:
//   - a degree-(t-1) polynomial f over Zr, master secret = a[0] = f(0)
//   - group_pk = f(0) * G1, 48-byte compressed G1 (KDD-049)
//   - n shares f(1)..f(n) as 32-byte big-endian scalars, 0-indexed in share_bytes
//
// The Lagrange x for share i is simply (i+1) — the natural polynomial evaluation
// point. There is no node_id, no alphabetical ordering, and therefore no
// index-space seam to reconcile (KDD-052 structurally eliminated post-KDD-069).
// Arithmetic mirrors the BLS threshold construction directly (blst).
// ---------------------------------------------------------------------------

static void gen_known_polynomial(int t, int n,
                                 uint8_t group_pk_bytes[48],
                                 std::vector<std::array<uint8_t, 32>>& share_bytes)
{
    // Coefficients a[0]..a[t-1] over Zr; master secret = a[0] = f(0).
    std::vector<blst_fr> coeffs(t);
    blst_scalar master_sk;
    for (int i = 0; i < t; ++i) {
        uint8_t ikm[32];
        GetStrongRandBytes(ikm, 32);
        blst_scalar tmp;
        blst_keygen(&tmp, ikm, 32, nullptr, 0);
        blst_fr_from_scalar(&coeffs[i], &tmp);
        if (i == 0)
            blst_scalar_from_fr(&master_sk, &coeffs[0]);
    }

    // group_pk = master_sk * G1, compressed to 48 bytes.
    blst_p1 pk_p1;
    blst_sk_to_pk_in_g1(&pk_p1, &master_sk);
    blst_p1_affine pk_aff;
    blst_p1_to_affine(&pk_aff, &pk_p1);
    blst_p1_affine_compress(group_pk_bytes, &pk_aff);

    // shares[i] = f(i+1) for i in [0, n-1].
    share_bytes.assign(n, std::array<uint8_t, 32>{});
    for (int i = 0; i < n; ++i) {
        int xi = i + 1;
        uint64_t xi_val[4] = {(uint64_t)xi, 0, 0, 0};
        blst_fr xi_fr;
        blst_fr_from_uint64(&xi_fr, xi_val);

        blst_fr share = coeffs[0];
        blst_fr xi_pow;
        { const uint64_t one[4] = {1, 0, 0, 0}; blst_fr_from_uint64(&xi_pow, one); }

        for (int j = 1; j < t; ++j) {
            blst_fr_mul(&xi_pow, &xi_pow, &xi_fr);   // xi^j
            blst_fr term;
            blst_fr_mul(&term, &coeffs[j], &xi_pow);
            blst_fr_add(&share, &share, &term);
        }
        blst_scalar sc;
        blst_scalar_from_fr(&sc, &share);
        blst_bendian_from_scalar(share_bytes[i].data(), &sc);
    }
}

// ---------------------------------------------------------------------------
// Harness integrity check.
//
// Uses already-generated state (group_pk_bytes, share_bytes) from the caller.
// Signs with the first t shares, recovers, verifies the valid sig, then
// corrupts recovered[0] ^= 0x01 and verifies again. Returns true only if the
// corrupted signature is correctly rejected.
//
// Called as the first statement of run_subset_exhaustion() so that every TV
// case independently enforces this gate before processing any subset.
// Execution order independence: if this returns false, BOOST_REQUIRE aborts
// the calling TV case; no TV can silently pass with a broken harness.
// ---------------------------------------------------------------------------

static bool harness_rejects_corruption(
    const uint8_t                              group_pk_bytes[48],
    const uint256&                             msg,
    const std::vector<std::array<uint8_t,32>>& share_bytes,
    int                                        t)
{
    std::vector<int>                  indices;
    std::vector<std::vector<uint8_t>> partial_sigs;
    indices.reserve(t);
    partial_sigs.reserve(t);

    for (int i = 0; i < t; ++i) {
        uint8_t sig[PTX_SIG_BYTES];
        if (!PTX_BLS_PartialSign(share_bytes[i].data(), msg, sig))
            return false;
        indices.push_back(i + 1);
        partial_sigs.emplace_back(sig, sig + PTX_SIG_BYTES);
    }

    uint8_t recovered[PTX_SIG_BYTES];
    if (!PTX_BLS_Recover(indices, partial_sigs, recovered))
        return false;

    // Valid signature must be accepted.
    if (!PTX_BLS_Verify(group_pk_bytes, msg, recovered))
        return false;

    // Corrupt one byte: must now be rejected.
    recovered[0] ^= 0x01;
    return !PTX_BLS_Verify(group_pk_bytes, msg, recovered);
}

// ---------------------------------------------------------------------------
// Falsification check — standalone case for named CI output only.
// Enforcement of the harness gate lives in run_subset_exhaustion().
// ---------------------------------------------------------------------------

BOOST_AUTO_TEST_CASE(BLSSubset_FalsificationCheck)
{
    const int t = 6, n = 11;

    uint8_t group_pk_bytes[48];
    std::vector<std::array<uint8_t, 32>> share_bytes;
    gen_known_polynomial(t, n, group_pk_bytes, share_bytes);
    BOOST_REQUIRE_EQUAL((int)share_bytes.size(), n);

    const uint256 msg = make_msg(0xAB);

    BOOST_REQUIRE_MESSAGE(
        harness_rejects_corruption(group_pk_bytes, msg, share_bytes, t),
        "FalsificationCheck: HARNESS BROKEN — PTX_BLS_Verify accepted a "
        "corrupted signature. All TV results are invalid.");
}

// ---------------------------------------------------------------------------
// Core subset runner.
// ---------------------------------------------------------------------------

static void run_subset_exhaustion(const char* tv_name,
                                  int t, int n, uint8_t msg_fill)
{
    // Generate the known polynomial: group_pk (48-byte compressed G1, KDD-049)
    // and all n shares. Test-local, no dealer symbol (KDD-069).
    uint8_t group_pk_bytes[48];
    std::vector<std::array<uint8_t, 32>> share_bytes;
    gen_known_polynomial(t, n, group_pk_bytes, share_bytes);
    BOOST_REQUIRE_EQUAL((int)share_bytes.size(), n);

    const uint256 msg = make_msg(msg_fill);

    // Harness integrity gate: enforced before any subset is processed.
    // If PTX_BLS_Verify cannot reject a corrupted sig, all subset results
    // are meaningless — abort this case immediately.
    BOOST_REQUIRE_MESSAGE(
        harness_rejects_corruption(group_pk_bytes, msg, share_bytes, t),
        tv_name << ": HARNESS BROKEN — PTX_BLS_Verify accepted a corrupted "
                   "signature. Subset results invalid. W1.2 gate blocked.");

    // Reference signature from subset 0 — all subsequent subsets must
    // produce byte-identical output (the defining property of t-of-n BLS).
    uint8_t first_sig[PTX_SIG_BYTES];
    int subset_count = 0;

    // Initial combination: 0-indexed {0, 1, ..., t-1}.
    std::vector<int> combo(t);
    std::iota(combo.begin(), combo.end(), 0);

    do {
        std::vector<int>                  indices;
        std::vector<std::vector<uint8_t>> partial_sigs;
        indices.reserve(t);
        partial_sigs.reserve(t);

        for (int idx : combo) {
            indices.push_back(idx + 1);  // 1-indexed polynomial position
            uint8_t sig[PTX_SIG_BYTES];
            BOOST_REQUIRE_MESSAGE(
                PTX_BLS_PartialSign(share_bytes[idx].data(), msg, sig),
                tv_name << " subset " << subset_count
                        << ": PartialSign failed for share " << (idx + 1));
            partial_sigs.emplace_back(sig, sig + PTX_SIG_BYTES);
        }

        uint8_t recovered[PTX_SIG_BYTES];
        BOOST_REQUIRE_MESSAGE(
            PTX_BLS_Recover(indices, partial_sigs, recovered),
            tv_name << " subset " << subset_count << ": Recover failed");

        BOOST_REQUIRE_MESSAGE(
            PTX_BLS_Verify(group_pk_bytes, msg, recovered),
            tv_name << " subset " << subset_count << ": Verify returned false");

        if (subset_count == 0) {
            memcpy(first_sig, recovered, PTX_SIG_BYTES);
        } else {
            BOOST_REQUIRE_MESSAGE(
                memcmp(recovered, first_sig, PTX_SIG_BYTES) == 0,
                tv_name << " subset " << subset_count
                        << ": recovered_sig differs from subset 0");
        }

        ++subset_count;
    } while (next_combination(combo, n));

    BOOST_TEST_MESSAGE(tv_name << " (t=" << t << ",n=" << n << "): "
                       << subset_count << "/" << subset_count << " subsets PASS");
}

// ---------------------------------------------------------------------------
// TV-1: t=6, n=11 — production parameters (KDD-048). C(11,6) = 462 subsets.
// ---------------------------------------------------------------------------

BOOST_AUTO_TEST_CASE(BLSSubset_TV1_t6_n11)
{
    run_subset_exhaustion("TV-1", 6, 11, 0xAB);
}

// ---------------------------------------------------------------------------
// TV-2: t=1, n=11 — degenerate lower bound. C(11,1) = 11 subsets.
// ---------------------------------------------------------------------------

BOOST_AUTO_TEST_CASE(BLSSubset_TV2_t1_n11)
{
    run_subset_exhaustion("TV-2", 1, 11, 0xCD);
}

// ---------------------------------------------------------------------------
// TV-3: t=11, n=11 — degenerate upper bound. C(11,11) = 1 subset.
// ---------------------------------------------------------------------------

BOOST_AUTO_TEST_CASE(BLSSubset_TV3_t11_n11)
{
    run_subset_exhaustion("TV-3", 11, 11, 0xEF);
}

BOOST_AUTO_TEST_SUITE_END()
