#!/usr/bin/env python3
"""W2 fleet generator — emits an isolated N-node ptx-w2 docker compose project.

Isolation spine (W2.0a, approved): the W2 fleet must NEVER collide with the
publicly running ptx-bea PoC (172.30.0.0/24, ports 30903-30914, named volumes)
or the ptxtestnet demo (172.28.0.0/24). Everything this generator emits is
namespaced ptx-w2: compose project `ptx-w2`, containers ptx-w2-*, network
ptx-w2-net on 172.31.0.0/24, host ports 31000+, bind-mount datadirs on
Node14TB. Verified free against live state 2026-07-06 (standup W2.0a entry).

Chain identity: reuses -ptxbea chainparams (same genesis/magic as the PoC).
Safe because the fleets share no P2P path: separate docker bridges, dnsseed=0,
intra-fleet addnode lists only, and the P2P port (29994) is never published
to the host. A separate chainparams class was considered and rejected (W2.0a
plan §2) — a consensus-code change buying nothing while the path is closed.

Topology: ring-plus-skips, not the PoC's star-on-gm01 — gm_i addnodes
gm_{i+1}, gm_{i+2}, gm_{i+4}, gm_{i+8} (mod N, 1-indexed). Connected at any
N >= 2, small diameter, ~4 outbound per node, no SPOF. The caller addnodes
three spread GMs. Validated post-bring-up by validate_fleet.py (Amendment 2:
a compose that comes up is not a mesh that works).

Regeneration is .env-safe: an existing .env (which carries the compound
node_ids captured at ProRegPL registration — the fleet's identity after the
Phase-2 restart) is NEVER overwritten; a fresh label-only .env is written
only if none exists.

Operator-key wiring (SG-0 Piece 1, GMAUTH-live): with --registration
<registration-NXX.json>, every GM service gains -gamemaster=1 and
-gmoperatorprivatekey=${GMxx_OPERATOR_SK:?...}, and the per-GM operator
secrets are APPENDED to .env (idempotent — only missing keys are added; the
.env-preserve invariant above holds). Secret flow: registration JSON -> .env
-> compose env-substitution, ALL host-side. This file carries ONLY the
variable-reference pattern, never a secret value. The caller gets no key
(it is not registered — separation of roles). Without --registration the
emitted compose is unchanged (GMAUTH-inert, pre-SG-0 behaviour).
"""

import argparse
import json
import os
import shutil
import sys

DEF_OUT = "/mnt/pve/Node14TB/hemis-ptx/docker-w2"
DEF_DATA_ROOT = "/mnt/pve/Node14TB/hemis-ptx/w2-fleet/datadirs"
DEF_SUBNET_BASE = "172.31.0"      # caller .10, gm_i .10+i  (N<=60 -> .70)
DEF_PORT_BASE = 31000             # caller 31000, gm_i 31000+i (N<=60 -> 31060)
DEF_IMAGE = "hemis-ptx-w2:40b109c"
DEF_RPCUSER = "ptxw2rpc"
DEF_RPCPASS = "ptxw2pass2026"     # fixture credential, isolated fleet (standup 2026-06-03 note)

SKIPS = (1, 2, 4, 8)

HEADER = """\
# GENERATED by testnet/w2fleet/gen_fleet.py — do not hand-edit; regenerate.
# ptx-w2 isolated W2 fleet: {n} GMs + caller. NEVER shares names/subnet/ports/
# volumes with the ptx-bea PoC (172.30.0.0/24, 30903-30914) or ptxtestnet
# (172.28.0.0/24). All lifecycle commands must carry -p ptx-w2.
name: ptx-w2

x-node-defaults: &node-defaults
  image: {image}
  restart: unless-stopped
  networks:
    - ptx-w2-net
  environment: &node-env
    RPCUSER: ${{RPCUSER:-{rpcuser}}}
    RPCPASSWORD: ${{RPCPASSWORD:?RPCPASSWORD must be set in .env}}

services:
"""


def gm_name(i):
    return f"gm{i:02d}"


def gm_ip(base, i):
    return f"{base}.{10 + i}"


def peers_of(i, n):
    """Ring-plus-skips peer set for gm_i (1-indexed), excluding self."""
    out = []
    for s in SKIPS:
        j = ((i - 1 + s) % n) + 1
        if j != i and j not in out:
            out.append(j)
    return out


def load_registration(path, n):
    """Validate the registration JSON covers gm01..gmNN with operator secrets.
    Returns the parsed dict. Secrets are only ever written to .env (host-side);
    callers must never print or embed them."""
    with open(path) as f:
        reg = json.load(f)
    missing = [gm_name(i) for i in range(1, n + 1)
               if not reg.get(gm_name(i), {}).get("operator_secret")]
    if missing:
        sys.exit(f"--registration {path} missing operator_secret for: "
                 f"{', '.join(missing)}")
    return reg


def ensure_env_operator_keys(env_path, reg, n):
    """Append missing GMxx_OPERATOR_SK lines to .env (idempotent; never
    rewrites existing lines — the compound-node_id preserve invariant)."""
    existing = ""
    if os.path.exists(env_path):
        with open(env_path) as f:
            existing = f.read()
    have = {ln.split("=", 1)[0] for ln in existing.splitlines() if "=" in ln}
    add = []
    for i in range(1, n + 1):
        g = gm_name(i)
        key = f"{g.upper()}_OPERATOR_SK"
        if key not in have:
            add.append(f"{key}={reg[g]['operator_secret']}")
    if add:
        with open(env_path, "a") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write("\n".join(add) + "\n")
    return len(add)


def emit_compose(n, image, subnet_base, port_base, data_root, rpcuser,
                 wire_operators=False):
    lines = [HEADER.format(n=n, image=image, rpcuser=rpcuser)]

    # ── caller ──────────────────────────────────────────────────────────
    caller_peers = sorted({1, (n // 2) or 1, n})
    lines.append(f"""\
  caller:
    <<: *node-defaults
    container_name: ptx-w2-caller
    hostname: caller
    networks:
      ptx-w2-net:
        ipv4_address: {subnet_base}.10
    volumes:
      - {data_root}/caller:/root/.hemis-ptxbea
    ports:
      - "{port_base}:29903"
    environment:
      <<: *node-env
      PTX_NODE_ID: ${{CALLER_NODE_ID:-caller}}
    command:
      - -externalip={subnet_base}.10
""")
    for p in caller_peers:
        lines.append(f"      - -addnode={gm_ip(subnet_base, p)}\n")
    lines.append("      # PTX node registry (legacy trusted-dealer roll path; id@host:port per KDD-033)\n")
    for i in range(1, n + 1):
        g = gm_name(i)
        lines.append(
            f"      - -ptxnode=${{{g.upper()}_NODE_ID:-{g}}}@{gm_ip(subnet_base, i)}:29903\n")
    lines.append("\n")

    # ── GMs ─────────────────────────────────────────────────────────────
    for i in range(1, n + 1):
        g = gm_name(i)
        lines.append(f"""\
  {g}:
    <<: *node-defaults
    container_name: ptx-w2-{g}
    hostname: {g}
    networks:
      ptx-w2-net:
        ipv4_address: {gm_ip(subnet_base, i)}
    volumes:
      - {data_root}/{g}:/root/.hemis-ptxbea
    ports:
      - "{port_base + i}:29903"
    environment:
      <<: *node-env
      PTX_NODE_ID: ${{{g.upper()}_NODE_ID:-{g}}}
    command:
      - -externalip={gm_ip(subnet_base, i)}
""")
        if wire_operators:
            # GMAUTH-live (SG-0 Piece 1): value comes from .env at compose
            # time — the reference pattern is the ONLY thing committed here.
            lines.append("      - -gamemaster=1\n")
            lines.append(f"      - -gmoperatorprivatekey="
                         f"${{{g.upper()}_OPERATOR_SK:?"
                         f"{g.upper()}_OPERATOR_SK must be set in .env}}\n")
        for p in peers_of(i, n):
            lines.append(f"      - -addnode={gm_ip(subnet_base, p)}\n")
        lines.append("\n")

    lines.append(f"""\
networks:
  ptx-w2-net:
    name: ptx-w2-net
    driver: bridge
    ipam:
      config:
        - subnet: {subnet_base}.0/24
""")
    return "".join(lines)


def emit_env(n, rpcuser, rpcpass):
    lines = [f"RPCUSER={rpcuser}", f"RPCPASSWORD={rpcpass}",
             "CALLER_NODE_ID=caller"]
    for i in range(1, n + 1):
        g = gm_name(i)
        lines.append(f"{g.upper()}_NODE_ID={g}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--n", type=int, required=True, help="GM count (22 floor, 60 ceiling tested)")
    ap.add_argument("--out", default=DEF_OUT)
    ap.add_argument("--data-root", default=DEF_DATA_ROOT)
    ap.add_argument("--subnet-base", default=DEF_SUBNET_BASE)
    ap.add_argument("--port-base", type=int, default=DEF_PORT_BASE)
    ap.add_argument("--image", default=DEF_IMAGE)
    ap.add_argument("--rpcuser", default=DEF_RPCUSER)
    ap.add_argument("--rpcpass", default=DEF_RPCPASS)
    ap.add_argument("--registration", default=None,
                    help="registration-NXX.json — wires -gamemaster=1 + "
                         "-gmoperatorprivatekey per GM (secrets to .env only)")
    args = ap.parse_args()

    if not (2 <= args.n <= 240):
        sys.exit("--n out of range (subnet /24: caller .10 + GMs .11..)")
    if args.subnet_base == "172.30.0" or args.port_base < 31000 and args.port_base + args.n >= 30903:
        sys.exit("refusing PoC-colliding subnet/ports")

    os.makedirs(args.out, exist_ok=True)
    os.makedirs(args.data_root, exist_ok=True)
    for name in ["caller"] + [gm_name(i) for i in range(1, args.n + 1)]:
        os.makedirs(os.path.join(args.data_root, name), exist_ok=True)

    reg = load_registration(args.registration, args.n) if args.registration else None

    compose_path = os.path.join(args.out, "docker-compose.generated.yml")
    with open(compose_path, "w") as f:
        f.write(emit_compose(args.n, args.image, args.subnet_base,
                             args.port_base, args.data_root, args.rpcuser,
                             wire_operators=reg is not None))

    env_path = os.path.join(args.out, ".env")
    if os.path.exists(env_path):
        print(f"[gen] {env_path} exists — PRESERVED (compound node_ids live here)")
    else:
        with open(env_path, "w") as f:
            f.write(emit_env(args.n, args.rpcuser, args.rpcpass))
        print(f"[gen] wrote fresh label-only {env_path}")

    if reg is not None:
        added = ensure_env_operator_keys(env_path, reg, args.n)
        print(f"[gen] operator keys wired for {args.n} GMs; "
              f"{added} GMxx_OPERATOR_SK line(s) appended to .env "
              f"(values host-side only)")

    # runtime docker assets ride along from the committed templates
    here = os.path.dirname(os.path.abspath(__file__))
    for asset in ("entrypoint.sh", "Dockerfile"):
        src = os.path.join(here, "docker", asset)
        dst = os.path.join(args.out, asset)
        shutil.copyfile(src, dst)
        os.chmod(dst, 0o755)

    print(f"[gen] N={args.n} caller={args.subnet_base}.10:{args.port_base} "
          f"gms=.11..{10+args.n}:{args.port_base+1}..{args.port_base+args.n}")
    print(f"[gen] compose: {compose_path}")
    print(f"[gen] data root: {args.data_root}")


if __name__ == "__main__":
    main()
