#!/usr/bin/env python3
"""W2 fleet generator — emits an isolated N-node ptx-w2 docker compose project.

Isolation spine (W2.0a, approved): the W2 fleet must NEVER collide with the
publicly running ptx-bea PoC (172.30.0.0/24, ports 30903-30914, named volumes)
or the ptxtestnet demo (172.28.0.0/24). Everything this generator emits is
namespaced ptx-w2: compose project `ptx-w2`, containers ptx-w2-*, network
ptx-w2-net on 172.31.0.0/24, host ports 31000+, bind-mount datadirs on
Node14TB. Verified free against live state 2026-07-06 (standup W2.0a entry).

Chain identity: reuses -ptxbea chainparams (same genesis/magic as the PoC).
Safe because the fleets share no P2P path: separate docker bridges, dnsseed=0,
intra-fleet addnode lists only, and the P2P port (29994) is never published
to the host. A separate chainparams class was considered and rejected (W2.0a
plan §2) — a consensus-code change buying nothing while the path is closed.

Topology: ring-plus-skips, not the PoC's star-on-gm01 — gm_i addnodes
gm_{i+1}, gm_{i+2}, gm_{i+4}, gm_{i+8} (mod N, 1-indexed). Connected at any
N >= 2, small diameter, ~4 outbound per node, no SPOF. The caller addnodes
three spread GMs. Validated post-bring-up by validate_fleet.py (Amendment 2:
a compose that comes up is not a mesh that works).

Regeneration is .env-safe: an existing .env (which carries the compound
node_ids captured at ProRegPL registration — the fleet's identity after the
Phase-2 restart) is NEVER overwritten; a fresh label-only .env is written
only if none exists.

Operator-key wiring (SG-0 Piece 1, GMAUTH-live): with --registration
<registration-NXX.json>, every GM service gains -gamemaster=1 and
-gmoperatorprivatekey=${GMxx_OPERATOR_SK:?...}, and the per-GM operator
secrets are APPENDED to .env (idempotent — only missing keys are added; the
.env-preserve invariant above holds). Secret flow: registration JSON -> .env
-> compose env-substitution, ALL host-side. This file carries ONLY the
variable-reference pattern, never a secret value. The caller gets no key
(it is not registered — separation of roles). Without --registration the
emitted compose is unchanged (GMAUTH-inert, pre-SG-0 behaviour).
"""

import argparse
import json
import os
import shutil
import sys

DEF_PROJECT = "ptx-w2"            # compose project + container/network prefix (--project for a 2nd instance)
DEF_OUT = "/mnt/pve/Node14TB/hemis-ptx/docker-w2"
DEF_DATA_ROOT = "/mnt/pve/Node14TB/hemis-ptx/w2-fleet/datadirs"
DEF_SUBNET_BASE = "172.31.0"      # caller .10, gm_i .10+i  (N<=60 -> .70)
DEF_PORT_BASE = 31000             # caller 31000, gm_i 31000+i (N<=60 -> 31060)
DEF_IMAGE = "hemis-ptx-w2:40b109c"
# subnets that MUST NOT be reused by a second instance (live fleets):
#   172.30.0 = ptx-bea PoC, 172.28.0 = ptxtestnet, 172.31.0 = live ptx-w2 fleet
RESERVED_SUBNETS = ("172.30.0", "172.28.0", "172.31.0")
DEF_RPCUSER = "ptxw2rpc"
DEF_RPCPASS = "ptxw2pass2026"     # fixture credential, isolated fleet (standup 2026-06-03 note)

# GMAUTH/member-connection era (2026-07-21, verdict-A build): offsets 1..11
# give every GM 11 addnodes — the deterministic PIGEONHOLE floor: at most 10
# of them can be co-members of any 11-selection, so >=1 non-member normal
# edge always survives ceremony conversion. TEST-FLEET COMPENSATION ONLY for
# two artifacts with zero production analog (peer discovery disabled + the
# shared-/16 netgroup cap, net.cpp:1732-47, that forbids addrman self-heal).
# NOT a production fix and NOT masking a gap — verdict-A: conversion churn is
# production-safe via inherited refill machinery.
SKIPS = tuple(range(1, 12))

HEADER = """\
# GENERATED by testnet/w2fleet/gen_fleet.py — do not hand-edit; regenerate.
# {project} isolated fleet: {n} GMs + caller. NEVER shares names/subnet/ports/
# volumes with other fleets (ptx-bea 172.30.0.0/24 30903-30914, ptxtestnet
# 172.28.0.0/24, live ptx-w2 172.31.0.0/24). All lifecycle commands carry -p {project}.
name: {project}

x-node-defaults: &node-defaults
  image: {image}
  restart: unless-stopped
  networks:
    - {project}-net
  environment: &node-env
    RPCUSER: ${{RPCUSER:-{rpcuser}}}
    RPCPASSWORD: ${{RPCPASSWORD:?RPCPASSWORD must be set in .env}}

services:
"""


def gm_name(i):
    return f"gm{i:02d}"


def gm_ip(base, i):
    return f"{base}.{10 + i}"


def peers_of(i, n):
    """Ring-plus-skips peer set for gm_i (1-indexed), excluding self."""
    out = []
    for s in SKIPS:
        j = ((i - 1 + s) % n) + 1
        if j != i and j not in out:
            out.append(j)
    return out


def load_registration(path, n):
    """Validate the registration JSON covers gm01..gmNN with operator secrets.
    Returns the parsed dict. Secrets are only ever written to .env (host-side);
    callers must never print or embed them."""
    with open(path) as f:
        reg = json.load(f)
    missing = [gm_name(i) for i in range(1, n + 1)
               if not reg.get(gm_name(i), {}).get("operator_secret")]
    if missing:
        sys.exit(f"--registration {path} missing operator_secret for: "
                 f"{', '.join(missing)}")
    return reg


def ensure_env_operator_keys(env_path, reg, n):
    """Append missing GMxx_OPERATOR_SK lines to .env (idempotent; never
    rewrites existing lines — the compound-node_id preserve invariant)."""
    existing = ""
    if os.path.exists(env_path):
        with open(env_path) as f:
            existing = f.read()
    have = {ln.split("=", 1)[0] for ln in existing.splitlines() if "=" in ln}
    add = []
    for i in range(1, n + 1):
        g = gm_name(i)
        key = f"{g.upper()}_OPERATOR_SK"
        if key not in have:
            add.append(f"{key}={reg[g]['operator_secret']}")
    if add:
        with open(env_path, "a") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write("\n".join(add) + "\n")
    return len(add)


def caller_name(k, callers):
    return "caller" if callers == 1 else f"caller{k}"


def emit_compose(n, image, subnet_base, port_base, data_root, rpcuser,
                 wire_operators=False, project=DEF_PROJECT, callers=1):
    lines = [HEADER.format(n=n, image=image, rpcuser=rpcuser, project=project)]

    # ── caller ──────────────────────────────────────────────────────────
    # KDD-064 session hardening (2026-07-18): 3 addnodes was single-points-of-
    # isolation fragile — when the caller forked (BUG-020 forensics), all 3
    # targets banning it meant TOTAL isolation.  7 spread peers is topology
    # robustness ONLY — it does NOT prevent the ban mechanism (more peers just
    # means more banners); the root fix is the KDD-064 maturity gate.
    caller_peers = sorted({1, 2, (n // 4) or 1, (n // 2) or 1,
                           ((n // 2) + 1) if n >= 2 else 1, (3 * n // 4) or 1, n})
    # One or more callers. Caller1 is the PRIMARY (ip .10, host port {port_base}) —
    # the harness drives the bootstrap through it. Additional callers are DRILL
    # REDUNDANCY (funded, staking-off spares): if a destructive experiment wedges
    # the primary, a spare takes over via a RESTORE instead of a re-bootstrap.
    # caller_k: ip .(10-(k-1)) (.10, .9, ...), host port {port_base}+n+(k-1) for k>1.
    for k in range(1, callers + 1):
        cname = caller_name(k, callers)
        cip = f"{subnet_base}.{10 - (k - 1)}"
        cport = port_base if k == 1 else port_base + n + (k - 1)
        cnid = "CALLER_NODE_ID" if callers == 1 else f"CALLER{k}_NODE_ID"
        lines.append(f"""\
  {cname}:
    <<: *node-defaults
    container_name: {project}-{cname}
    hostname: {cname}
    networks:
      {project}-net:
        ipv4_address: {cip}
    volumes:
      - {data_root}/{cname}:/root/.hemis-ptxbea
    ports:
      - "{cport}:29903"
    environment:
      <<: *node-env
      PTX_NODE_ID: ${{{cnid}:-{cname}}}
    command:
      - -externalip={cip}
      - -staking=0
""")
        for p in caller_peers:
            lines.append(f"      - -addnode={gm_ip(subnet_base, p)}\n")
        lines.append("      # PTX node registry (legacy trusted-dealer roll path; id@host:port per KDD-033)\n")
        for i in range(1, n + 1):
            g = gm_name(i)
            lines.append(
                f"      - -ptxnode=${{{g.upper()}_NODE_ID:-{g}}}@{gm_ip(subnet_base, i)}:29903\n")
        lines.append("\n")

    # ── GMs ─────────────────────────────────────────────────────────────
    for i in range(1, n + 1):
        g = gm_name(i)
        lines.append(f"""\
  {g}:
    <<: *node-defaults
    container_name: {project}-{g}
    hostname: {g}
    networks:
      {project}-net:
        ipv4_address: {gm_ip(subnet_base, i)}
    volumes:
      - {data_root}/{g}:/root/.hemis-ptxbea
    ports:
      - "{port_base + i}:29903"
    environment:
      <<: *node-env
      PTX_NODE_ID: ${{{g.upper()}_NODE_ID:-{g}}}
    command:
      - -externalip={gm_ip(subnet_base, i)}
""")
        if wire_operators:
            # GMAUTH-live (SG-0 Piece 1): value comes from .env at compose
            # time — the reference pattern is the ONLY thing committed here.
            lines.append("      - -gamemaster=1\n")
            lines.append(f"      - -gmoperatorprivatekey="
                         f"${{{g.upper()}_OPERATOR_SK:?"
                         f"{g.upper()}_OPERATOR_SK must be set in .env}}\n")
        for p in peers_of(i, n):
            lines.append(f"      - -addnode={gm_ip(subnet_base, p)}\n")
        lines.append("\n")

    lines.append(f"""\
networks:
  {project}-net:
    name: {project}-net
    driver: bridge
    ipam:
      config:
        - subnet: {subnet_base}.0/24
""")
    return "".join(lines)


def emit_env(n, rpcuser, rpcpass, callers=1):
    lines = [f"RPCUSER={rpcuser}", f"RPCPASSWORD={rpcpass}"]
    if callers == 1:
        lines.append("CALLER_NODE_ID=caller")
    else:
        for k in range(1, callers + 1):
            lines.append(f"CALLER{k}_NODE_ID=caller{k}")
    for i in range(1, n + 1):
        g = gm_name(i)
        lines.append(f"{g.upper()}_NODE_ID={g}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--n", type=int, required=True, help="GM count (22 floor, 60 ceiling tested)")
    ap.add_argument("--project", default=DEF_PROJECT,
                    help="compose project + container/network prefix; use a distinct value "
                         "(e.g. bf) for a SECOND, isolated instance")
    ap.add_argument("--callers", type=int, default=1,
                    help="caller count (1 = primary only; 2+ adds funded staking-off "
                         "spares for drill redundancy — a wedged primary restores, not re-bootstraps)")
    ap.add_argument("--out", default=DEF_OUT)
    ap.add_argument("--data-root", default=DEF_DATA_ROOT)
    ap.add_argument("--subnet-base", default=DEF_SUBNET_BASE)
    ap.add_argument("--port-base", type=int, default=DEF_PORT_BASE)
    ap.add_argument("--image", default=DEF_IMAGE)
    ap.add_argument("--rpcuser", default=DEF_RPCUSER)
    ap.add_argument("--rpcpass", default=DEF_RPCPASS)
    ap.add_argument("--registration", default=None,
                    help="registration-NXX.json — wires -gamemaster=1 + "
                         "-gmoperatorprivatekey per GM (secrets to .env only)")
    args = ap.parse_args()

    if not (2 <= args.n <= 240):
        sys.exit("--n out of range (subnet /24: caller .10 + GMs .11..)")
    # A SECOND instance (--project != default) must not reuse any live fleet's
    # subnet — structural isolation guard (bfleet must not land on live 172.31.0).
    if args.project != DEF_PROJECT and args.subnet_base in RESERVED_SUBNETS:
        sys.exit(f"refusing: --project {args.project} on reserved live subnet "
                 f"{args.subnet_base}.0/24 (live fleets: {', '.join(RESERVED_SUBNETS)})")
    if args.subnet_base == "172.30.0" or (args.port_base < 31000 and args.port_base + args.n >= 30903):
        sys.exit("refusing PoC-colliding subnet/ports")

    os.makedirs(args.out, exist_ok=True)
    os.makedirs(args.data_root, exist_ok=True)
    caller_dirs = [caller_name(k, args.callers) for k in range(1, args.callers + 1)]
    for name in caller_dirs + [gm_name(i) for i in range(1, args.n + 1)]:
        os.makedirs(os.path.join(args.data_root, name), exist_ok=True)

    reg = load_registration(args.registration, args.n) if args.registration else None

    compose_path = os.path.join(args.out, "docker-compose.generated.yml")
    with open(compose_path, "w") as f:
        f.write(emit_compose(args.n, args.image, args.subnet_base,
                             args.port_base, args.data_root, args.rpcuser,
                             wire_operators=reg is not None, project=args.project,
                             callers=args.callers))

    env_path = os.path.join(args.out, ".env")
    if os.path.exists(env_path):
        print(f"[gen] {env_path} exists — PRESERVED (compound node_ids live here)")
    else:
        with open(env_path, "w") as f:
            f.write(emit_env(args.n, args.rpcuser, args.rpcpass, callers=args.callers))
        print(f"[gen] wrote fresh label-only {env_path}")

    if reg is not None:
        added = ensure_env_operator_keys(env_path, reg, args.n)
        print(f"[gen] operator keys wired for {args.n} GMs; "
              f"{added} GMxx_OPERATOR_SK line(s) appended to .env "
              f"(values host-side only)")

    # runtime docker assets ride along from the committed templates
    here = os.path.dirname(os.path.abspath(__file__))
    for asset in ("entrypoint.sh", "Dockerfile"):
        src = os.path.join(here, "docker", asset)
        dst = os.path.join(args.out, asset)
        shutil.copyfile(src, dst)
        os.chmod(dst, 0o755)

    print(f"[gen] N={args.n} caller={args.subnet_base}.10:{args.port_base} "
          f"gms=.11..{10+args.n}:{args.port_base+1}..{args.port_base+args.n}")
    print(f"[gen] compose: {compose_path}")
    print(f"[gen] data root: {args.data_root}")


if __name__ == "__main__":
    main()
