// Copyright (c) 2012-2017 The Bitcoin Core developers
// Copyright (c) 2016-2021 The Hemis Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include "clientversion.h"

#include "tinyformat.h"


/**
 * Name of client reported in the 'version' message. Report the same name
 * for both Hemisd and Hemis-qt, to make it harder for attackers to
 * target servers or GUI users specifically.
 */
const std::string CLIENT_NAME(PACKAGE_NAME);

/**
 * Client version number
 */
#define CLIENT_VERSION_SUFFIX ""


/**
 * The following part of the code determines the CLIENT_BUILD variable.
 * Several mechanisms are used for this:
 * * first, if HAVE_BUILD_INFO is defined, include build.h, a file that is
 *   generated by the build environment, possibly containing the output
 *   of git-describe in a macro called BUILD_DESC
 * * secondly, if this is an exported version of the code, GIT_ARCHIVE will
 *   be defined (automatically using the export-subst git attribute), and
 *   GIT_COMMIT will contain the commit id.
 * * then, three options exist for determining CLIENT_BUILD:
 *   * if BUILD_DESC is defined, use that literally (output of git-describe)
 *   * if not, but GIT_COMMIT is defined, use v[maj].[min].[rev].[build]-g[commit]
 *   * otherwise, use v[maj].[min].[rev].[build]-unk
 * finally CLIENT_VERSION_SUFFIX is added
 */

//! First, include build.h if requested
#ifdef HAVE_BUILD_INFO
#include "obj/build.h"
#endif

//! git will put "#define GIT_ARCHIVE 1" on the next line inside archives.
// ★★ THE `#define GIT_ARCHIVE 1` THAT USED TO SIT HERE WAS COMMITTED BY MISTAKE,
// AND IT MADE EVERY GIT-LESS BUILD LIE ABOUT ITS OWN COMMIT.
// Upstream keeps that define inside the comment above and lets `git archive`
// substitute it in (.gitattributes marks this file export-subst). Here both the
// define AND the substituted values were committed -- GIT_COMMIT_ID below is
// frozen at a 3 Sep 2023 hash that does not exist in this repository -- so
// GIT_ARCHIVE was ALWAYS defined and GIT_COMMIT_ID always available.
//
// It only showed when a build had no git metadata. The precedence at :63-69
// takes BUILD_DESC from obj/build.h first, which genbuild.sh fills in whenever
// git is readable, so an ordinary checkout was always right. Build from an
// exported tree and it fell through to the 2023 constant and reported it as
// authoritative. Measured 2026-08-23: a `git archive` shipment built to
// "v1.3.1.0-g652c668d3ebf51f0b168e7ff00ffdc86e45daa4f"; the same source from a
// real clone built to "v1.3.1.0-ec980b9".
//
// ★ That is not a cosmetic label. Identifying a STALE BINARY by its version
// string is how the 4d558e6 retraction was reached that same day -- the daemon
// said 60ff2a1, which predated the fix it appeared to be missing. That
// diagnostic worked only because .git happened to be present.
//
// Removing the define makes a git-less build report "-unk" (BUILD_DESC_FROM_UNKNOWN,
// :60) -- honest, and obviously unusable as provenance. It cannot change an
// ordinary build: BUILD_DESC from obj/build.h still wins, and configure.ac:482
// sets -DHAVE_BUILD_INFO unconditionally with src/Makefile.am:392-396
// regenerating build.h every time. Release builds are unaffected either way --
// .github/workflows/build-and-release.yml uses actions/checkout@v4 with
// fetch-depth: 0, a full clone.
//
// ★ NOT restored to the upstream `$Format:%H$` form, which would be the fuller
// fix: that makes `git archive` substitute correctly, but any tarball produced
// WITHOUT git substitution would then carry the literal "$Format:%H$" in its
// version string. Left for a deliberate decision rather than taken here.
#ifdef GIT_ARCHIVE
#define GIT_COMMIT_ID "652c668d3ebf51f0b168e7ff00ffdc86e45daa4f"
#define GIT_COMMIT_DATE "Sun, 3 Sep 2023 08:37:37 -0400"
#endif

#define BUILD_DESC_WITH_SUFFIX(maj, min, rev, build, suffix) \
    "v" DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" DO_STRINGIZE(suffix)

#define BUILD_DESC_FROM_COMMIT(maj, min, rev, build, commit) \
    "v" DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-g" commit

#define BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build) \
    "v" DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-unk"

#ifndef BUILD_DESC
#ifdef BUILD_SUFFIX
#define BUILD_DESC BUILD_DESC_WITH_SUFFIX(CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR, CLIENT_VERSION_REVISION, CLIENT_VERSION_BUILD, BUILD_SUFFIX)
#elif defined(GIT_COMMIT_ID)
#define BUILD_DESC BUILD_DESC_FROM_COMMIT(CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR, CLIENT_VERSION_REVISION, CLIENT_VERSION_BUILD, GIT_COMMIT_ID)
#else
#define BUILD_DESC BUILD_DESC_FROM_UNKNOWN(CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR, CLIENT_VERSION_REVISION, CLIENT_VERSION_BUILD)
#endif
#endif

const std::string CLIENT_BUILD(BUILD_DESC CLIENT_VERSION_SUFFIX);

static std::string FormatVersion(int nVersion)
{
    if (nVersion % 100 == 0)
        return strprintf("%d.%d.%d", nVersion / 1000000, (nVersion / 10000) % 100, (nVersion / 100) % 100);
    else
        return strprintf("%d.%d.%d.%d", nVersion / 1000000, (nVersion / 10000) % 100, (nVersion / 100) % 100, nVersion % 100);
}

std::string FormatFullVersion()
{
    return CLIENT_BUILD;
}

std::string FormatVersionFriendly()
{
    return FormatVersion(CLIENT_VERSION);
}

/** 
 * Format the subversion field according to BIP 14 spec (https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki) 
 */
std::string FormatSubVersion(const std::string& name, int nClientVersion, const std::vector<std::string>& comments)
{
    std::ostringstream ss;
    ss << "/";
    ss << name << ":" << FormatVersion(nClientVersion);
    if (!comments.empty()) {
        std::vector<std::string>::const_iterator it(comments.begin());
        ss << "(" << *it;
        for (++it; it != comments.end(); ++it)
            ss << "; " << *it;
        ss << ")";
    }
    ss << "/";
    return ss.str();
}
